### ISSUE TITLE
How can I use the WeightedRandomSampler in fastai fit func?

### ISSUE THREAD

**Issue by robeson1010** [TheShadow29/FAI-notes#1]

**Comment by TheShadow29** [comment]
Are you using new fastai (v1) or the older one (0.7)? Both would have similar approach. Define a DataLoader, and then pass it to the DataBunch (for v1) and ModelData for (v0.7).

To be specific: 
```
trn_dl = DataLoader(trn_ds, sampler=sampler)
val_dl = DataLoader(val_ds, sampler=sampler)
data = DataBunch(trn_dl, val_dl, path=path)
```
In the older one use `data = ModelData(path, trn_dl, val_dl)`.

**Comment by robeson1010** [comment]
Thanks~

**Comment by TheShadow29** [comment]
Closing the issue then.
