### ISSUE TITLE
ModuleNotFoundError after trying to import fastai.transforms

### ISSUE THREAD

**Issue by yasaswinir** [TheShadow29/FAI-notes#2]
I followed the same method as you stated but i get this error. Any ideas how to deal with this?

**Comment by TheShadow29** [comment]
I would need more details to help you out. Could you tell the fastai version you are using. There is a new one fastai-v1, this repo is based on the older fastai-v0.7. Also, which module is not found? Maybe, just install that module separately?

**Comment by yasaswinir** [comment]
I cloned the fastai folder from github and ran the environments.yml file in a virtual environment that i created. The version is 1.0.39, the recent one in git. I tried running the lesson1 code in practical machine learning for coders course but it says Module not Found error for any other Modules such as fastai.transforms , fastai.module...etc... I only don't get that error for importing fastai.imports

**Comment by TheShadow29** [comment]
I would suggest asking this in `https://forums.fast.ai/`. The repo is based off an older version of fastai (0.7). To my knowledge, installation of the new version should not require cloning the github repository, simple conda installation is sufficient. Best to ask in the forums.

**Comment by yasaswinir** [comment]
okay.Thank you very much
